# Removes pending-response and closing-soon labels when an issue is closed.

name: Add issue to applicable project

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  project:
    name: Add to project 
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request && (contains(github.event.label.name, 'amplify/')) }}

    steps:
      - uses: actions/checkout@v3
      - name: Add issue to project
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh issue edit $ISSUE_NUMBER --add-project "fooproject"
