on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.print_tags }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 

  log-level:
    runs-on: ubuntu-latest
    steps:
      - name: Echo logLevel
        run: echo logLevel is ${{ inputs.logLevel }}

  log-level-info:
    if: ${{ inputs.logLevel = 'info' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo info
        run: echo info ${{ inputs.logLevel }}

  log-level-warning:
    if: ${{ inputs.logLevel = 'warning' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo warning
        run: echo warning ${{ inputs.logLevel }}

  log-level-debug:
    if: ${{ inputs.logLevel = 'debug' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo debug
        run: echo debug ${{ inputs.logLevel }}
