on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        default: true
        type: boolean
  push:
    branches: [main]

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ github.event_name != 'workflow_dispatch' || inputs.print_tags }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are  

  log-level:
    runs-on: ubuntu-latest
    steps:
      - name: Echo logLevel
        run: echo logLevel is ${{ inputs.logLevel }}

  log-level-info:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.logLevel == 'info' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo info
        run: echo info ${{ inputs.logLevel }}

  log-level-warning:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.logLevel == 'warning' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo warning
        run: echo warning ${{ inputs.logLevel }}

  log-level-debug:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.logLevel == 'debug' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo debug
        run: echo debug ${{ inputs.logLevel }}
