on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'OS'
        required: true
        default: 'warning'
        type: choice
        options:
          - iOS
          - watchOS
          - tvOS
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        default: true
        type: boolean
  push:
    branches: [main]

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ github.event_name != 'workflow_dispatch' || inputs.print_tags }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are  

  log-level:
    runs-on: ubuntu-latest
    steps:
      - name: Echo OS
        run: echo OS is ${{ inputs.OS }}

  os-iOS:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.OS == 'info' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo iOS
        run: echo iOS ${{ inputs.OS }}

  os-watchOS:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.OS == 'warning' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo watchOS
        run: echo watchOS ${{ inputs.OS }}

  os-tvOS:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.OS == 'debug' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo tvOS
        run: echo tvOS ${{ inputs.OS }}
