on:
  workflow_dispatch:
    inputs:
      ios:
        description: '📱 iOS'
        required: true
        default: true
        type: boolean
      tvos:
        description: '📺 tvOS'
        required: true
        default: true
        type: boolean
      watchos:
        description: '⌚️ watchOS'
        required: true
        default: true
        type: boolean
  push:
    branches: [main]

jobs:
  os-iOS:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.ios }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo iOS
        run: echo iOS ${{ inputs.ios }}

  os-tvOS:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.tvos }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo tvOS
        run: echo tvOS ${{ inputs.tvos }}

  os-watchOS:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.watchos }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo watchOS
        run: echo watchOS ${{ inputs.watchos }}
