on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System 📱 📺 ⌚️ '
        required: true
        default: 'iOS'
        type: choice
        options:
          - iOS
          - watchOS
          - tvOS
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        default: true
        type: boolean
  push:
    branches: [main]

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ github.event_name != 'workflow_dispatch' || inputs.print_tags }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are  

  log-level:
    runs-on: ubuntu-latestq
    steps:
      - name: Echo OS
        run: echo OS is ${{ inputs.os }}

  os-iOS:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.os == 'iOS' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo iOS
        run: echo iOS ${{ inputs.os }}

  os-watchOS:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.os == 'watchOS' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo watchOS
        run: echo watchOS ${{ inputs.os }}

  os-tvOS:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.os == 'tvOS' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo tvOS
        run: echo tvOS ${{ inputs.os }}
