name: Notify New Issues

on:
  issues:
    types: [opened]

permissions: 
  issues: write

jobs:
  maintainer-opened:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request && contains(fromJSON('["palpatim", "brennanMKE", "diegocstn", "lawmicha", "harsh62", "thisisabhash", "ameter", "royjit", "atierian", "ukhan-amazon", "ruisebas", "phantumcode"]'), github.event.issue.user.login) }}
    steps:
      - name: remove unnecessary labels after closing
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh issue comment $ISSUE_NUMBER --repo atierian/actiontest -b "This issue was opened by a maintainer of this repository. Updates will be posted here.\nIf you are also experiencing this issue, please comment here so that we're aware and can prioritize accordingly."
